# Generated by Django 6.1.1 on 2026-09-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='intake_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
